spring:
  application:
    name: gateway
  # Cloud Gateway Configuration
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: https://auth-pajw42smtq-ew.a.run.app
              predicates:
                - Path=/api/auth/**
            - id: jobs-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/jobs/**
            - id: model-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/model/**

# Security Configuration
security:
  jwt:
    expiration-time: 86400000

# Server Configuration
server:
  tomcat:
    max-connections: 10000
    accept-count: 100
    max-threads: 200
    min-spare-threads: 10
  compression:
    enabled: true

# Logging Configuration
logging:
  level:
    com.tecazuay.gateway.logging: DEBUG
    org.springframework.web: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Resilience4j Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      default:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
